import math 
a=input('Введите значения а ')
a=float(a)
b=input('Введите значения b ')
b=float(b)
c=input('Введите значения c ')
c=float(c)
coA = (-a*a+b*b+c*c)/(2*b*c) 
radA=math.acos(coA)
corA=radA*(180/math.pi)
print('Угол А в градусах ',corA)
print('Угол А в радианах ',radA)
coB= (-b*b+a*a+c*c)/(2*a*c)
radB=math.acos(coB)
corB=radB*(180/math.pi)
print('Угол В в градусах ',corB)
print('Угол В в радианах ',radB)
coC=(-c*c+a*a+b*b)/(2*b*a)
radC=math.acos(coC)
corC=radC*(180/math.pi)
print('Угол С в градусах ',corC)
print('Угол С в радианах ',radC)
